Portfolio project Landing page
DaveZag/Portfolio-setup-and-mobile-first pull request #2
Opened 2022-08-18 21:24 UTC by DaveZag

# Portfolio Landing page
> ### We used [template 2](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) for this project.
## In this branch:
- We set up Html and CSS files(With their respective linter to ease code writing and bug catching) ;
- We set up external styling files for icons;
- We Mark and Style the header and its components( Logo, Navbar);
-  We Mark and Style the landing page hero and its components( Main Title and supporting texts);
- We Run [HTML & CSS ](https://github.com/microverseinc/linters-config/tree/master/html-css) linters and fix all markdown and stylistic errors;
-  Ignore all unnecessary dependency files to avoid tracking and Pushing/uploading them to the remote repo.

....

2022-08-18 21:41 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @DaveZag 👋🏻
Great job so far, you're doing great 💯  There are some changes that need to be implemented in order to proceed to the next project 👍🏻 

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️
* Professional PR description ✔️ 

## Required Changes:
_Please check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 21:41 UTC, ha-manel commented on style.css
> +  font-size: 1.125rem;
- [ ] Great job on styling your headline, it looks awesome 💯  However, we are required to follow the Figma design. kindly use the same font sizes that are used in Figma, same thing goes for all the texts in the page 👍🏻

2022-08-18 21:41 UTC, ha-manel commented on index.html
> +      </div>
- [ ] Good job on adding a nav menu 👍🏻 However, it's not in the requirements yet, kindly remove it and wrap the menu button in the `nav` tag instead😄

2022-08-18 21:57 UTC, DaveZag commented on style.css
> +  font-size: 1.125rem;
> Thanks for the reply. 🙂

### Concerning the font sizes, I was referring to Figma but used a px to rem convertor. Should I stick to pixels?

2022-08-18 22:02 UTC, ha-manel commented on style.css
> +  font-size: 1.125rem;
I'm not sure but I think you can use rem as long as it will be the same in px as in the Figma design, if you inspect the page and hover over the texts it will show you the sizes in px and you will see the difference 😄

2022-08-18 22:35 UTC, DaveZag commented on index.html
> +      </div>
Hello @ha-manel,
### I made all the changes as required:
- Fixed the sizing errors;
- Removed the unordered list from Nav;
- Wrapped the div with the class of  "menu-btn-container" in it.

2022-08-18 22:56 UTC, ha-manel commented on index.html
> +      </div>
Great job! Please submit the same PR link in your dashboard to get a re-review 👏🏻

2022-08-19 00:29 UTC, MaganaAsiati approved these changes
## Hi @DaveZag  👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>

# Congratulations! 🎉 

✔️ No linter errors
✔️ Professional pull request title and description
✔️  Good commit message 
✔️ Good use of Github flow 

### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 03:18 UTC, merged